### ISSUE TITLE
Tabs are not getting hidden.

### ISSUE THREAD

**Issue by Jzarecta** [vdw/Tabslet#21]
I am trying to get this plugin to work for several days now. I am unable to get the tabs to hide even with the initialization.js I still get all the divs displayed. I also tried inserting the javascript inline still get no result.
Is there a CSS missing exactly how many CSS do I need to get the div effect to work?

**Comment by vdw** [comment]
Hi, normally Tabslet does **not** require any CSS in order to function correctly.

[Here](https://jsfiddle.net/dkrestos/buu48sa0/1/) is an example of Tabslet in action **without** CSS (please, pay attention on html structure, href and id tags).

Beyond that, could you provide me with a URL or a JSFiddle with your example?
