### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by yoanntalagrand** [vdw/Tabslet#23]
Would you consider implementing deep linking in order to open the right tab based on the anchor link?

**Comment by vdw** [comment]
Yes, of course, we need this in order to use browser's history with back/forward buttons - but if you just need to open a specific tab on the page load, you can use the "active" option as data attribute in the DOM.

E.g.:

    <div data-toggle="tabslet" data-active="dynamic_value">
      // your html for tabs
    </div>

Where "dynamic_value" is a value (the index number of a tab) generated by your server side code (php, ruby etc) or by a javascript code based on the url parameters/anchor.

**Comment by flowdee** [comment]
Would be amazing to get deeplinking! +1

There are many ppl how like to share links like e.g. http://example.com/test/#second-tab

**Comment by vdw** [comment]
Deep linking support is added in version [1.6.0](https://github.com/vdw/Tabslet/tree/v1.6.0).

You can enable deep linking support by setting the option "deeplinking" to true.

Note: Deep linking support overrides the options "active" and "data-active".

**Comment by flowdee** [comment]
Thanks so far, really cool! Would you mind adding an option (or make it default when deeplinking is active) that the hash will be added to the current browser url? 

e.g. after submitting a form the current page url will load again but without the hash in the url, the active tab won't come back after the submission.

**Comment by vdw** [comment]
@flowdee This functionality has added in version [1.6.1](https://github.com/vdw/Tabslet/tree/v1.6.1).

**Comment by flowdee** [comment]
Thanks for your great work @vdw :+1:

**Comment by serran0** [comment]
Hmm, using deeplinking the tabs still wont change usgin back/forward browser buttons. The hash changes but not the tabs. Is this by design?
Using latest Chrome.
