### ISSUE TITLE
Unable to get hash deeplinking working

### ISSUE THREAD

**Issue by djhsecondnature** [vdw/Tabslet#48]
Hi there,

I'm unable to get any hash deeplinking working (e.g. domain.com/page#tab-2) to activate that tab. Is it not a feature of the plugin or am I doing something wrong in setup?

Cheers

**Comment by vdw** [comment]
Hi, 

it would be helpful if you could share some code or link, otherwise it is hard to tell you what is wrong. However, I can provide you with a working example of deep-linking enabled on Tabslet.

Here it is: http://superintendant-panda-15833.netlify.com/#tab-2

Notes:
1. If you change the last part of uri to `#tab-3` and make the call then it loads the page with the last tab active.
2. It you click on the first tab then the uri should change to `...tlify.com/#tab-1`

More notes:
To enable deep-linking you should set the deep-linking option to true, `deeplinking:  true`

**Comment by djhsecondnature** [comment]
Ah - I didn't know you needed to set that setting (it's not in the documentation).

Thanks :-)
